name: cycletowork
description: A new open source app for track bicycle.
publish_to: 'https://github.com/mondora/cycletowork'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: '2.10.3'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  provider: ^6.0.2
  firebase_core: ^1.13.1
  cloud_functions: ^3.2.10
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9
  firebase_remote_config: ^2.0.2
  firebase_auth: ^3.3.11
  google_sign_in: ^5.2.4
  sign_in_with_apple: ^3.3.0
  crypto: ^3.0.1
  flutter_dotenv: ^5.0.2
  auth_buttons: ^2.0.4
  flutter_native_splash: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true