name: cycletowork
description: A new open source app for track bicycle.
publish_to: 'https://github.com/mondora/cycletowork'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: '2.10.3'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  provider: ^6.0.3
  firebase_core: ^1.20.0
  cloud_functions: ^3.3.3
  cloud_firestore: ^3.4.1
  firebase_remote_config: ^2.0.13
  firebase_auth: ^3.5.1
  google_sign_in: ^5.4.0
  sign_in_with_apple: ^4.1.0
  crypto: ^3.0.2
  flutter_dotenv: ^5.0.2
  auth_buttons: ^3.0.0
  flutter_native_splash: ^2.2.6
  localstore: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  background_image: assets/images/splash_screen.png
  background_image_dark: assets/images/splash_screen_dark.png
  android_12:
  fullscreen: true