name: cycletowork
description: A new open source app for track bicycle.
publish_to: 'https://github.com/mondora/cycletowork'
version: 1.0.10+44

environment:
    sdk: '>=2.18.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    intl: ^0.17.0
    cupertino_icons: ^1.0.5
    google_fonts: ^3.0.1
    provider: ^6.0.3
    firebase_core: ^1.21.1
    cloud_functions: ^3.3.6
    firebase_auth: ^3.7.0
    google_sign_in: ^5.4.1
    flutter_dotenv: ^5.0.2
    flutter_native_splash: ^2.2.9
    url_launcher: ^6.1.5
    location: 5.0.0-dev.8
    geocoding: ^2.0.5
    flutter_svg: ^1.1.4
    sliding_up_panel: ^2.0.0+1
    charts_flutter: ^0.12.0
    google_maps_flutter: ^2.2.0
    maps_toolkit: ^2.0.1
    shimmer: ^2.0.0
    flutter_inset_box_shadow: ^1.0.8
    share_plus: ^4.1.0
    sqflite: ^2.0.3+1
    uuid: ^3.0.6
    shared_preferences: ^2.0.15
    logger: ^1.1.0
    firebase_messaging: ^13.0.0
    flutter_local_notifications: ^9.9.1
    badges: ^2.0.3
    flutter_otp_text_field: ^1.1.0+2
    auto_size_text: ^3.0.0
    firebase_crashlytics: ^2.8.9
    app_settings: ^4.1.8
    filter_list: ^1.0.2
    webview_flutter: ^3.0.4
    path_provider: ^2.0.11
    path: ^1.8.2
    flutter_native_image: ^0.0.6+1
    firebase_storage: ^10.3.8
    camera: ^0.10.0+1
    permission_handler: ^10.0.0
    image_picker: ^0.8.5+3
    wakelock: ^0.6.2
    flutter_activity_recognition: ^1.3.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^1.0.0

flutter:
    uses-material-design: true
    generate: true
    assets:
        - .env
        - assets/images/
        - assets/icons/
        - assets/maps/

flutter_native_splash:
    background_image: assets/images/splash_screen.png
    background_image_dark: assets/images/splash_screen_dark.png
    android_12:
    fullscreen: true
