name: cycletowork
description: A new open source app for track bicycle.
publish_to: 'https://github.com/mondora/cycletowork'
version: 1.2.6+83

environment:
    sdk: '>=2.18.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    intl: ^0.17.0
    cupertino_icons: ^1.0.5
    google_fonts: ^3.0.1
    provider: ^6.0.4
    firebase_core: ^2.1.1
    cloud_functions: ^4.0.3
    firebase_auth: ^4.1.1
    google_sign_in: ^5.4.2
    flutter_dotenv: ^5.0.2
    flutter_native_splash: ^2.2.9
    url_launcher: ^6.1.6
    geolocator: ^9.0.2
    geocoding: ^2.0.5
    flutter_svg: ^1.1.5
    sliding_up_panel: ^2.0.0+1
    charts_flutter: ^0.12.0
    google_maps_flutter: ^2.2.1
    google_maps_flutter_android: ^2.3.2
    google_maps_flutter_platform_interface: ^2.2.4
    maps_toolkit: ^2.0.1
    shimmer: ^2.0.0
    flutter_inset_box_shadow: ^1.0.8
    share_plus: ^6.0.1
    sqflite: ^2.1.0+1
    uuid: ^3.0.6
    shared_preferences: ^2.0.15
    logger: ^1.1.0
    firebase_messaging: ^14.0.4
    flutter_local_notifications: ^12.0.2
    badges: ^2.0.3
    flutter_otp_text_field: ^1.1.1
    auto_size_text: ^3.0.0
    firebase_crashlytics: ^3.0.4
    app_settings: ^4.1.8
    filter_list: ^1.0.2
    webview_flutter: ^3.0.4
    path_provider: ^2.0.11
    path: ^1.8.2
    flutter_native_image: ^0.0.6+1
    firebase_storage: ^11.0.3
    camera: ^0.10.0+3
    permission_handler: ^10.2.0
    image_picker: ^0.8.6
    wakelock: ^0.6.2
    flutter_activity_recognition: ^1.3.0
    package_info_plus: ^3.0.1
    vibration: ^1.7.6
    device_info_plus: ^8.0.0
    firebase_analytics: ^10.0.4

dev_dependencies:
    integration_test:
        sdk: flutter
    flutter_test:
        sdk: flutter
    flutter_lints: ^1.0.0
    path_provider_android: ^2.0.20

flutter:
    uses-material-design: true
    generate: true
    assets:
        - .env
        - assets/images/
        - assets/icons/
        - assets/maps/

flutter_native_splash:
    background_image: assets/images/splash_screen.png
    background_image_dark: assets/images/splash_screen_dark.png
    android_12:
    fullscreen: true
